# Generated by Django 5.1.2 on 2024-11-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
