# Generated by Django 5.1.2 on 2024-11-01 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_dosage_medicine_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='when_to_take',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 0, 39, 50, 863382)),
            preserve_default=False,
        ),
    ]
